#!/usr/bin/env bash
## Script for updating local elpa mirror
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2020 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

cp dotspacemacs.el ~/.spacemacs

mkdir -p "testelpa"

ln -s "${GITHUB_WORKSPACE}/spacemacs" "${HOME}/.emacs.d"

emacs --batch \
      -l "${HOME}/.emacs.d/init.el" \
      -l "${HOME}/elpa-mirror.el" \
      --eval="(setq elpamr-default-output-directory \"testelpa\")" \
      --eval="(elpamr-create-mirror-for-installed)"
